
run:
	python3 $(SCRIPT)


clean:
	rm -f *.pyc __pycache__/*

# Help target to provide user the method to use this file
help:
	@echo "Usage:"
	@echo "  make run SCRIPT=<script_name.py>  - Run the specified Python script"
	@echo "  make clean                       - Clean up temporary files"

