all : Lab2 boothmultiplier memorymaze

Lab2 : Lab2.c
	@gcc -o Lab2 Lab2.c

boothmultiplier : boothmultiplier.c
	@gcc -o boothmultiplier boothmultiplier.c

memorymaze : memorymaze.c
	@gcc -o memorymaze memorymaze.c

clean : 
	@rm -f Lab2 boothmultiplier memorymaze