
# Default target (display readme file for help)
help :
	cat readme.md

# Shorthand targets (see readme)
bm : boothmultiplier
cs : cache_simulator
nrd : non_restoringdivision

# Targets for python scripts
boothmultiplier : boothmultiplier.py
	@python boothmultiplier.py

cache_simulator: cache_simulator.py
	@python cache_simulator.py

non_restoringdivision : non_restoringdivision.py
	@python non_restoringdivision.py

# clean
clean :
	@echo "Nothing to clean"